name: Extract Keys Workflow

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    name: Update Keys
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: |
        echo '{}' > package.json
        npm install node-fetch@2 webcrack
        pnpm install
    - name: Run extraction script
      run: node index.mjs > keys.json
      id: extract-keys

    - name: Verify keys.json
      run: |
        echo "Content of keys.json after extraction script:"
        cat keys.json
      # Debugging step to check the content of keys.json

    - name: Commit and push changes if there are changes
      run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add keys.json
          git commit --allow-empty -m "Update keys.json"
          git stash
          git pull --rebase
          git stash pop || true
          git add keys.json
          git commit --allow-empty -m "Update keys.json"
          git push
        # Stash changes, pull latest, apply stash, commit and push

    - name: Clean up unnecessary files
      run: |
          rm -rf node_modules
          rm package-lock.json
      if: always() # Ensure cleanup runs even if previous steps fail
